name: Aviator Test Uploader
description: Uploads your JUnit files to Aviator
author: https://github.com/buildkite-plugins
requirements:
  - curl
  - zip
configuration:
  properties:
    api-key-env-name:
      type: string
    api-url:
      type: string
    files:
      type: string
  required:
    - files
  additionalProperties: false
